---
name: CI/Linting, Testing, Building Artifacts
on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/build-and-publish.yml'

concurrency:
  group: ${{ github.workflow }}

env:
  DOCKERHUB_REPO: 'theodore86/aws-route53'
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  
jobs:
  linting_and_testing:
    uses: ./.github/workflows/linting-and-testing.yml
  build_and_publish_docker_image:
    needs: ['linting_and_testing']
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout SCM'
        uses: 'actions/checkout@v3.5.2'

      - name: 'Login to docker registry'
        uses: 'docker/login-action@v2.1.0'
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
          logout: true

      - name: 'Retrieve latest commit sha as image tag'
        id: 'git_short_sha'
        run: |
          short_sha=$(git log -1 --format=%h)
          echo "::set-output name=short_sha::$short_sha"

      - name: 'Build and push docker image'
        uses: 'docker/build-push-action@v4.1.1'
        with:
          push: true
          context: .
          file: Dockerfile
          no-cache: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ steps.git_short_sha.outputs.short_sha }}
            ${{ env.DOCKERHUB_REPO }}:latest
...
